application: octopus
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: main.application

- url: /static/
  static_dir: static

libraries:
- name: MySQLdb
  version: "latest"