application: octopus-1340
version: 1
runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  MYSQL_USER: root
  MYSQL_HOST: localhost

handlers:
- url: /static/
  static_dir: static

- url: /.*
  script: main.application


libraries:
- name: MySQLdb
  version: "latest"
- name: pycrypto
  version: "2.6"
